services:
  db: 
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: desafio-codecon
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - desafio-codecon
  api:
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - desafio-codecon
    depends_on:
      - db
networks:
  desafio-codecon:
    driver: bridge
