services:
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - desafio-codecon
    volumes:
      - mongodb_data:/data/db
  api:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASS: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB: ${MONGO_INITDB_DATABASE}
    networks:
      - desafio-codecon
    depends_on:
      - db
networks:
  desafio-codecon:
    driver: bridge
volumes:
  mongodb_data:
